# Generated by Django 4.1.5 on 2023-01-22 17:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=255, verbose_name='Страна')),
                ('city', models.CharField(max_length=255, verbose_name='Город')),
                ('street', models.CharField(max_length=255, verbose_name='Улица')),
                ('street_number', models.CharField(max_length=255, verbose_name='Номер дома')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('model', models.CharField(max_length=255, verbose_name='Модель')),
                ('release_date', models.DateTimeField(verbose_name='Дата выхода на рынок')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта')),
                ('address', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='distribution_chain.address', verbose_name='Адрес')),
            ],
        ),
        migrations.CreateModel(
            name='ChainLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('level', models.PositiveSmallIntegerField(choices=[(0, 'Завод'), (1, 'Дистрибьютор'), (2, 'Дилерский центр'), (3, 'Крупная розничная сеть'), (4, 'Индивидуальный предприниматель')], verbose_name='Уровень')),
                ('owed', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Задолженность')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('contact', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='distribution_chain.contact', verbose_name='Контакты')),
                ('employees', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Сотрудники')),
                ('product', models.ManyToManyField(to='distribution_chain.product', verbose_name='Продукт')),
                ('supplier', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='distribution_chain.chainlink', verbose_name='Поставщик')),
            ],
        ),
    ]
