# Generated by Django 4.1.5 on 2023-01-22 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('distribution_chain', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chainlink',
            name='employees',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL, verbose_name='Сотрудники'),
        ),
        migrations.AlterField(
            model_name='chainlink',
            name='owed',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=19, verbose_name='Задолженность'),
        ),
        migrations.AlterField(
            model_name='chainlink',
            name='product',
            field=models.ManyToManyField(blank=True, null=True, to='distribution_chain.product', verbose_name='Продукт'),
        ),
        migrations.AlterField(
            model_name='chainlink',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='distribution_chain.chainlink', verbose_name='Поставщик'),
        ),
    ]
