# Generated by Django 4.1.5 on 2023-01-22 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distribution_chain', '0002_alter_chainlink_employees_alter_chainlink_owed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chainlink',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribution_chain.contact', verbose_name='Контакты'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distribution_chain.address', verbose_name='Адрес'),
        ),
    ]
