# Generated by Django 4.1.5 on 2023-01-22 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('distribution_chain', '0003_alter_chainlink_contact_alter_contact_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chainlink',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='distribution_chain.contact', verbose_name='Контакты'),
        ),
    ]
