# Generated by Django 4.1.5 on 2023-01-23 05:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('distribution_chain', '0005_remove_contact_address_remove_chainlink_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='release_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата выхода на рынок'),
        ),
    ]
