# Generated by Django 4.1.5 on 2023-01-23 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('distribution_chain', '0007_remove_chainlink_employees_remove_chainlink_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chainlink',
            old_name='product',
            new_name='products',
        ),
    ]
